# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

version: '2.1'

services:

  # PHP & apache container using offical Docker PHP image
  web:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not Buildcontainer see Dockerflile
    image: openenergymonitor/emoncms:latest
    build: .
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfiwa:/var/lib/phpfiwa
      - emon-phpfina:/var/lib/phpfina
      - emon-phptimeseries:/var/lib/phptimeseries
    links:
      # Link to MYSQL DB (see below)
      - db
      - redis
    networks:
      - mrossi-net

  # MYSQL Database
  db:
    # Official MYSQL docker image
    # To do: make compatiable with 5.7
    image: mariadb:10
    environment:
      - "MYSQL_HOST=localhost"
    volumes:
      - emon-db-data:/var/lib/mysql
    networks:
      - mrossi-net
    healthcheck:
      test: "mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD"
      timeout: 20s
      retries: 10
      
  redis:
    # Official redis image
    image: redis:5
    volumes:
      - emon-redis-data:/data
    networks:
      - mrossi-net
  # PHP container using offical Docker PHP image for the MQTT integration
  mqtt:
    #    
    image: openenergymonitor/emoncms-mqtt:latest
    build: 
      context: ./
      dockerfile: ./mqtt/Dockerfile
    depends_on:
      db:
        condition: service_healthy  
    volumes:
      # mount docker volumes persistant inside docker container
      - emon-phpfiwa:/var/lib/phpfiwa
      - emon-phpfina:/var/lib/phpfina
      - emon-phptimeseries:/var/lib/phptimeseries
    networks:
      - mrossi-net

volumes:
  emon-phpfiwa:
    driver: local
  emon-phpfina:
    driver: local
  emon-phptimeseries:
    driver: local
  emon-db-data:
    driver: local
  emon-redis-data:
    driver: local

networks:
  mrossi-net:
    external: true
